name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["feature-**", "fix-**", staging, master]
  schedule:
    # At 02:30 on Saturday
    - cron: "30 2 * * 6"

jobs:
  build-fluent-bit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

      - name: Set Docker image name
        id: set-image
        run: |
          echo  "GITHUB_REF:${GITHUB_REF}"
          echo  "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          VERSION_TAG=${GITHUB_REF#refs/*/}
          SHA_SHORT="${GITHUB_SHA::7}"
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          echo "sha_short=${SHA_SHORT:?}" >> $GITHUB_OUTPUT
          echo "docker_image=ghcr.io/${ORG:?}/loki-fluent-bit-input" >> $GITHUB_OUTPUT
          if [[ ${VERSION_TAG%/merge} == 'master' ]]; then
            echo "docker_tag=latest" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} == 'staging' ]]; then
            echo "docker_tag=staging" >> $GITHUB_OUTPUT
          fi

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Container metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
        with:
          images: ${{ steps.set-image.outputs.docker_image }}
          labels: |
            maintainer=Josh.5
            source.version=${{ steps.set-image.outputs.sha_short }}
            source.project=grafana-docker-swarm
            source.service=loki-fluent-bit-input
            org.opencontainers.image.title=loki-fluent-bit-input

      - name: Build and push Container image
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          platforms: linux/amd64,linux/arm64
          context: docker/fluent-bit
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.set-image.outputs.docker_image }}:${{ steps.set-image.outputs.docker_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-swarm-stack-templates:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build-fluent-bit]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Swarm Template
        uses: Josh5/action.publish-swarm-stack@4392d434d4cfc8df552c7e92cf063428343f96d2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          templates_path: docker-swarm-templates
          branch_name: release/latest
